name: Selenium Grid via ORAS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  selenium-grid:
    runs-on: ubuntu-latest

    steps:
      # -----------------------
      # Checkout Repo
      # -----------------------
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------
      # Install ORAS CLI
      # -----------------------
      - name: Install ORAS
        run: |
          curl -sSfL https://github.com/oras-project/oras/releases/latest/download/oras_linux_amd64.tar.gz \
            | sudo tar -xz -C /usr/local/bin oras

      # -----------------------
      # Login to GHCR using ORAS
      # -----------------------
      - name: Login to GHCR with ORAS
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      # -----------------------
      # Pull Selenium Grid (Hub + Nodes) from ORAS
      # Example repo: ghcr.io/<OWNER>/selenium-grid
      # -----------------------
      - name: Pull Selenium Grid Hub (ORAS artifact)
        run: |
          oras pull ghcr.io/${{ github.repository_owner }}/selenium-hub:latest \
            --output /tmp/selenium-hub

      - name: Pull Selenium Chrome Node
        run: |
          oras pull ghcr.io/${{ github.repository_owner }}/selenium-node-chrome:latest \
            --output /tmp/selenium-node-chrome

      - name: Pull Selenium Firefox Node
        run: |
          oras pull ghcr.io/${{ github.repository_owner }}/selenium-node-firefox:latest \
            --output /tmp/selenium-node-firefox

      # -----------------------
      # Start Selenium Grid Containers
      # -----------------------
      - name: Start Selenium Hub
        run: |
          docker run -d --name selenium-hub -p 4444:4444 -p 4443:4443 \
            -v /tmp/selenium-hub:/opt/selenium \
            selenium/hub:latest

      - name: Start Chrome Node
        run: |
          docker run -d --name chrome-node --shm-size="2g" \
            --link selenium-hub:hub \
            -v /tmp/selenium-node-chrome:/opt/selenium \
            -e SE_EVENT_BUS_HOST=hub \
            -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
            -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
            selenium/node-chrome:latest

      - name: Start Firefox Node
        run: |
          docker run -d --name firefox-node --shm-size="2g" \
            --link selenium-hub:hub \
            -v /tmp/selenium-node-firefox:/opt/selenium \
            -e SE_EVENT_BUS_HOST=hub \
            -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
            -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
            selenium/node-firefox:latest

      # -----------------------
      # Wait for Grid
      # -----------------------
      - name: Wait for Selenium Grid to be Ready
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:4444/status | jq -e '.value.ready' >/dev/null; then
              echo "Grid is ready!"
              exit 0
            fi
            echo "Waiting for Grid..."
            sleep 3
          done
          echo "Grid not ready in time!" && exit 1

      # -----------------------
      # Run your tests
      # -----------------------
      - name: Run Java Tests
        if: always()
        run: mvn test

      - name: Run Python Tests
        if: always()
        run: |
          pip install -r requirements.txt
          pytest -s --disable-warnings

      # -----------------------
      # Upload test reports (optional)
      # -----------------------
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/surefire-reports
            test-reports
