name: Selenium Grid Using ORAS

on: [workflow_dispatch, push]

jobs:
  run-grid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Install ORAS
      - name: Install ORAS CLI
        run: |
          curl -sSL https://oras.land/install.sh | sh
          sudo mv oras /usr/local/bin/

      # Authenticate to OCI registry (GHCR example)
      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} |
          oras login ghcr.io -u ${{ github.actor }} --password-stdin

      # Pull Selenium Hub image from ORAS/OCI registry
      - name: ORAS Pull Selenium Grid Hub Image
        run: |
          oras pull ghcr.io/<owner>/<repo>/selenium-hub:latest \
            --output /tmp/selenium-hub.tar

      # Load image into Docker
      - name: Load Hub image into Docker
        run: |
          docker load -i /tmp/selenium-hub.tar

      # Start Selenium Hub
      - name: Start Selenium Hub
        run: |
          docker run -d --name selenium-hub -p 4444:4444 selenium-hub:latest

      # Pull Node Chrome image
      - name: ORAS Pull Selenium Node Chrome
        run: |
          oras pull ghcr.io/<owner>/<repo>/selenium-node-chrome:latest \
            --output /tmp/node-chrome.tar

      - name: Load Chrome node image
        run: docker load -i /tmp/node-chrome.tar

      # Start Node Chrome
      - name: Start Selenium Node Chrome
        run: |
          docker run -d \
            --name node-chrome \
            --net=host \
            -e SE_EVENT_BUS_HOST=localhost \
            -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
            -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
            selenium-node-chrome:latest

      # Wait for Selenium Hub
      - name: Wait for Grid Health
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4444/status | jq '.value.ready' | grep true; then
              echo "Grid is ready!";
              exit 0;
            fi
            echo "Waiting for Selenium Grid..."
            sleep 2
          done
          exit 1

      # Your tests (Java, Python, etc.)
      - name: Run Tests
        run: |
          echo "Run your test runner here"
